# https://xuri.me/toml-to-go/

[System]
Addr=":3718"
LogPath="./logs/holydramon.log"
IsDebug=true
[Mysql]
Enable=true
Dsn="root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4"
MaxLifetime=20
MaxIdle=20
MaxOpen=20
[Wx]
Token="holydramon"
AppId="xxxxxxxxxxx"
AppSecret="xxxxxxxxx"
[Oss]
Ak="xxxxxxxxx"
Sk="xxxxxxxxxxx"
EndPoint="oss-cn-beijing-internal.aliyuncs.com"
BucketName="holydramon"
[Domains]
ShortUrl="tiyee.cn/"
ImgHttps="https://img.tiyee.cn/"
ImgHttp="http://img.tiyee.cn/"