name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
#https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${ GITHUB_REF/refs\/tags\//}
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: ${{steps.get_version.outputs.VERSION}}
        release_name: ${{steps.get_version.outputs.VERSION}}
        draft: false
        prerelease: false
